secretaria/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

handler404 = 'secretariaapp.views.erro404'
handler500 = 'secretariaapp.views.erro500'

urlpatterns = [

    path('admin/', admin.site.urls),
    url(r'^', include('secretariaapp.urls')),#incluir rotas do app
]

secretariaapp/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views
from django.http import Http404


#nome do app
app_name='secretariaapp'

handler404 = 'secretariaapp.views.erro404'


#array
urlpatterns = [

    url(r'^$',index,name='index'),
    #url('igrejaelshaday.org', index,name='igrejaelshaday'),

    url(r'^login',auth_views.login,{'template_name': 'login.html'},name='login'),
    #url(r'^logout',auth_views.logout,{'template_name': 'index.html'},name='logout'),
    url(r'^logout',redirecionar,name='logout'),

    url(r'^recuperarsenha/(?P<recuperar>[0-9a-z]+)/$',recuperarsenha,name='recuperarsenha'),



    url(r'^sempermissao$',login_required(sempermissao),name='sempermissao'),
    url(r'^relatorios/(?P<imprimir>[relatorios,imprimir]+)/$',login_required(relatorios),name='relatorios'),
    url(r'^aniversariantes$',login_required(aniversariantes), name='aniversariantes'),
    url(r'^esqueceusenha$',esqueceuSenha,name='esqueceuSenha'),
    url(r'^suporte$',suporte,name='suporte'),


    url(r'^user/update/(?P<pk>[0-9]+)/$',login_required(UserUpdate.as_view()),name='userUpdate'),
    #url(r'^meu_user/update/(?P<pk>[0-9]+)/$',login_required(MeuUserUpdate.as_view()),name='meu_userUpdate'),
    url(r'^meu_user/update/$',login_required(meuUserUpdate),name='meu_perfil'),#nao generica
    url(r'^user/new/$',login_required(UserCreate.as_view()),name='userNew'),
    #url(r'^user/(?P<pk>[0-9]+)/$',login_required(userDetalhes),name='userDetalhes'),
    #url(r'^user/$',login_required(user),name='user'),
    url(r'^user/delete/(?P<pk>[0-9]+)/$',login_required(UserDelete.as_view()), name='userDelete'),
    #url(r'^user/meu_perfil/$',login_required(meu_perfil), name='meu_perfil'),

    #url(r'^perfil/alternativa/(?P<pk>[0-9]+)/$',login_required(perfilAlternativa),name='perfilAlternativa'),

    url(r'^meu_perfil/$',login_required(meu_perfilDetalhes),name='meu_perfilDetalhes'),
    #url(r'^meu_perfil/update/(?P<pk>[0-9]+)/$',login_required(MeuPerfilUpdate.as_view()),name='meu_perfilUpdate'),
    url(r'^meu_perfil/update/$',login_required(meuPerfilUpdate),name='meu_perfilUpdate'),

    url(r'^perfil/update/(?P<pk>[0-9]+)/$',login_required(PerfilUpdate.as_view()),name='perfilUpdate'),
    url(r'^perfil/(?P<pk>[0-9]+)/$',login_required(perfilDetalhes),name='perfilDetalhes'),
    url(r'^perfil/$',login_required(perfil),name='perfil'),


    url(r'^membros/new/$',login_required(MembroCreate.as_view()),name='membroNew'),
    url(r'^membros/(?P<pk>[0-9]+)/$',login_required(membroDetalhes),name='membroDetalhes'),
    #url(r'^membros/$',login_required(membro),name='membros'),
    url(r'^membros/$',login_required(membro),name='membros'),
    url(r'^membros/update/(?P<pk>[0-9]+)/$',login_required(MembroUpdate.as_view()),name='membroUpdate'),
    url(r'^membros/delete/(?P<pk>[0-9]+)/$',login_required(MembroDelete.as_view()), name='membroDelete'),

    url(r'^membro_grupo_pequeno_especifico/new/(?P<pk>[0-9]+)/$',login_required(membro_grupo_pequeno_especificoNew),name='membro_grupo_pequeno_especificoNew'),
    url(r'^membro_grupo_pequeno/new/$',login_required(membro_grupo_pequenoNew),name='membro_grupo_pequenoNew'),
    url(r'^membro_especifico_no_grupo_pequeno/new/(?P<pk>[0-9]+)/$',login_required(membro_especifico_no_grupo_pequenoNew),name='membro_especifico_no_grupo_pequenoNew'),


    url(r'^ministerios/new/$',login_required(MinisterioCreate.as_view()),name='ministerioNew'),
    url(r'^ministerios/(?P<pk>[0-9]+)/$',login_required(ministerioDetalhes),name='ministerioDetalhes'),
    url(r'^ministerios/$',login_required(ministerio),name='ministerios'),
    url(r'^ministerios/update/(?P<pk>[0-9]+)/$',login_required(MinisterioUpdate.as_view()),name='ministerioUpdate'),
    url(r'^ministerios/delete/(?P<pk>[0-9]+)/$',login_required(MinisterioDelete.as_view()), name='ministerioDelete'),


    url(r'^obreiro_ou_lider_delete/(?P<mt>[0-9]+)/(?P<mb>[0-9]+)/(?P<opc>[0-9]+)/$',login_required(obreiroOuLiderDelete),name='obreiroOuLiderDelete'),
    url(r'^obreiro_ou_lider_adicionar/(?P<mt>[0-9]+)/(?P<mb>[0-9]+)/(?P<opc>[0-9]+)/$',login_required(obreiroOuLiderAdicionar),name='obreiroOuLiderAdicionar'),

    url(r'^lider_gp_delete/(?P<gp>[0-9]+)/(?P<mb>[0-9]+)/$',login_required(liderGrupoPequenoDelete),name='liderGrupoPequenoDelete'),
    url(r'^lider_gp_adicionar/(?P<gp>[0-9]+)/(?P<mb>[0-9]+)/$',login_required(liderGrupoPequenoAdicionar),name='liderGrupoPequenoAdicionar'),



    url(r'^grupos_pequenos/new/$',login_required(Grupo_PequenoCreate.as_view()),name='grupo_pequenoNew'),
    url(r'^grupos_pequenos/(?P<pk>[0-9]+)/$',login_required(grupo_pequenoDetalhes),name='grupo_pequenoDetalhes'),
    url(r'^grupos_pequenos/$',login_required(grupo_pequeno),name='grupo_pequeno'),
    url(r'^grupos_pequenos/update/(?P<pk>[0-9]+)/$',login_required(Grupo_PequenoUpdate.as_view()),name='grupo_pequenoUpdate'),
    url(r'^grupos_pequenos/delete/(?P<pk>[0-9]+)/$',login_required(Grupo_PequenoDelete.as_view()), name='grupo_pequenoDelete'),

    url(r'^remover_membro_pg/(?P<pk_m>[0-9]+)/(?P<pk_pg>[0-9]+)/$',login_required(remover_membro_pg), name='remover_membro_pg'),


]

secretariaapp/models.py
from django.db import models
from datetime import date
from datetime import datetime
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Trilha_Discipulado(models.Model):
    trilha_discipulado = models.CharField(max_length=100,unique=True)
    descricao = models.TextField(blank=True)
    def __str__(self):
        return str(self.trilha_discipulado)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.trilha_discipulado = self.trilha_discipulado.upper()
        super(Trilha_Discipulado, self).save(force_insert, force_update)


class Situacao(models.Model):
    situacao = models.CharField(max_length=100,unique=True)
    descricao = models.TextField(blank=True)
    def __str__(self):
        return str(self.situacao)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.situacao = self.situacao.upper()
        super(Situacao, self).save(force_insert, force_update)

class Grupo_Pequeno(models.Model):
    nome = models.CharField(max_length=100,unique=True)
    descricao = models.TextField(blank=True)
    def __str__(self):
        return str(self.nome)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.nome = self.nome.upper()
        super(Grupo_Pequeno, self).save(force_insert, force_update)

class Origem(models.Model):
    origem = models.CharField(max_length=30,unique=True)
    descricao = models.TextField(blank=True)
    def __str__(self):
        return str(self.origem)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.origem = self.origem.upper()
        super(Origem, self).save(force_insert, force_update)



class Sexo(models.Model):
    sexo = models.CharField(max_length=10,unique=True)
    def __str__(self):
        return str(self.sexo)


class Uf(models.Model):
    uf = models.CharField(max_length=2,unique=True)
    estado = models.CharField(max_length=30,unique=True)
    #estado = models.CharField(max_length=30)
    def __str__(self):
        return str(self.uf)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.uf = self.uf.upper()
        super(Uf, self).save(force_insert, force_update)



class Estado_Civil(models.Model):
    estado_civil = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return str(self.estado_civil)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.estado_civil = self.estado_civil.upper()
        super(Estado_Civil, self).save(force_insert, force_update)


class Escolaridade(models.Model):
    escolaridade = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return str(self.escolaridade)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.escolaridade = self.escolaridade.upper()
        super(Escolaridade, self).save(force_insert, force_update)

class Ministerio(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True)
    areas_atuacao = models.CharField(max_length=100,blank=True)
    obs = models.TextField(blank=True)
    def __str__(self):
        return str(self.nome)

    def save(self, force_insert=False, force_update=False):
        self.nome = self.nome.upper()
        super(Ministerio, self).save(force_insert, force_update)


class Membro(models.Model):
    nome_completo = models.CharField(max_length=100 )
    sexo = models.ForeignKey(Sexo, on_delete=models.PROTECT)
    situacao = models.ForeignKey(Situacao, on_delete=models.PROTECT)
    data_situacao = models.DateField(blank=True,null=True)
    data_nascimento = models.DateField(default=datetime.now,blank=True,null=True)
    naturalidade = models.CharField(max_length=30,blank=True)
    uf_nascimento = models.ForeignKey(Uf, related_name = 'uf_nascimento', on_delete=models.PROTECT,null=True,blank=True)
    cpf = models.CharField(max_length=11,blank=True)
    rg = models.CharField(max_length=15,blank=True)
    endereco = models.CharField(max_length=50,blank=True)
    n = models.CharField(max_length=10,blank=True)
    bairro = models.CharField(max_length=50,blank=True)
    cidade = models.CharField(max_length=50)
    uf_endereco = models.ForeignKey(Uf, related_name = 'uf_endereco', on_delete=models.PROTECT)
    cep = models.CharField(max_length=10,blank=True)
    telefone_celular = models.CharField(max_length=15,blank=True)
    telefone_residencial = models.CharField(max_length=15,blank=True)
    telefone_comercial = models.CharField(max_length=15,blank=True)
    email = models.EmailField(max_length=254,blank=True)
    nome_responsavel = models.CharField(max_length=100,blank=True)
    estado_civil = models.ForeignKey(Estado_Civil, on_delete=models.PROTECT)
    nome_conjuge = models.CharField(max_length=100,blank=True)
    data_casamento = models.DateField(blank=True,null=True)

    numero_filhos = models.PositiveIntegerField(default= 0)
    filho1 = models.CharField(max_length=100,blank=True)
    data_nascimento_filho1 = models.DateField(blank=True,null=True)
    filho2 = models.CharField(max_length=100,blank=True)
    data_nascimento_filho2 = models.DateField(blank=True,null=True)
    filho3 = models.CharField(max_length=100,blank=True)
    data_nascimento_filho3 = models.DateField(blank=True,null=True)
    outros_filhos = models.TextField(blank=True)

    escolaridade = models.ForeignKey(Escolaridade, on_delete=models.PROTECT)
    profisao = models.CharField(max_length=50,blank=True)
    economicamente_ativo = models.BooleanField(default = False)

    data_conversao = models.DateField(default=datetime.now,blank=True,null=True)
    data_batismo = models.DateField(default=datetime.now,blank=True,null=True)
    igreja_batismo = models.CharField(max_length=50,blank=True)
    pastor = models.CharField(max_length=100,blank=True)
    data_chegada_na_elshaday = models.DateField(default=datetime.now,blank=True,null=True)
    origem = models.ForeignKey(Origem, on_delete=models.PROTECT,blank=True,null=True)
    ministerios_que_deseja_participar = models.CharField(max_length=100, blank=True)
    ministerios = models.ManyToManyField(Ministerio, blank=True)
    ministerios_que_lidera = models.ManyToManyField(Ministerio, blank=True, related_name='lider_ministario')

    participa_grupo_pequeno = models.BooleanField(default = False)
    grupo_pequeno = models.ForeignKey(Grupo_Pequeno, on_delete=models.PROTECT,blank=True,null=True)
    grupos_pequenos_que_lidera = models.ManyToManyField(Grupo_Pequeno, blank=True, related_name='grupo_pequeno_lider')

    trilha_discipulado = models.ManyToManyField(Trilha_Discipulado, blank=True)

    obs = models.TextField(blank=True)

    def __str__(self):
        return str(self.nome_completo)
    #funcao que faz com que os campos sejam Maiusculo automaticamente
    def save(self, force_insert=False, force_update=False):
        self.nome_completo = self.nome_completo.upper()
        super(Membro, self).save(force_insert, force_update)

'''
class Lider_Grupo_Pequeno(models.Model):
    lider = models.ForeignKey(Membro,related_name = 'lider', on_delete=models.CASCADE)
    grupo_pequeno = models.ForeignKey(Grupo_Pequeno, on_delete=models.CASCADE)
    obs = models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.lider) +' LIDER DO(A) '+ str(self.grupo_pequeno )



class Lider_Ministerio(models.Model):
    nome_lider = models.ForeignKey(Membro,related_name = 'nome_lider', on_delete=models.CASCADE)
    ministerio = models.ForeignKey(Ministerio, on_delete=models.CASCADE)
    obs = models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.nome_lider) +' LIDER DO '+ str(self.ministerio )


    def save(self, force_insert=False, force_update=False):
        try:
            x = Lider_Ministerio.objects.get(ministerio = self.ministerio, nome_lider = self.nome_lider )
        except Exception as e:
            super(Lider_Ministerio, self).save(force_insert, force_update)
            #So salva se nao tiver nenhum ingual
        #nao faz nada se tiver repetido


class Obreiro_Ministerio(models.Model):
    obreiro = models.ForeignKey(Membro,related_name = 'obreiro', on_delete=models.CASCADE)
    ministerio = models.ForeignKey(Ministerio, on_delete=models.CASCADE)
    obs = models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.obreiro) +' OBREIRO DO '+ str(self.ministerio )
'''


class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=100, blank=True,null=True)
    email = models.EmailField(max_length=254,blank=True,null=True)
    gerenciar_Membros = models.BooleanField(default = False)
    gerenciar_Grupos_Pequenos = models.BooleanField(default = False)
    gerenciar_Ministerios = models.BooleanField(default = False)
    gerenciar_Relatorios = models.BooleanField(default = False)
    gerenciar_Usuarios = models.BooleanField(default = False)
    recuperar = models.CharField(max_length=100,blank=True,null=True)
    data_recuperar = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.user.username

#usar isso para criar automaticamente um perfil
@receiver(post_save, sender=User)
def create_user_perfil(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(user=instance)

secretariaapp/templates/grupo_pequeno_detalhes.html
{% include 'cabecalho.html' %}
<div class="corpo_app">
        <h2>Dados do Grupo Pequeno</h2>

        <div class="field">
          <label>Nome do Grupo Pequeno: </label>
          {{grupo_pequeno.nome}}
        </div>

        <div class="field">
          <label>Descrição: </label>
          {{grupo_pequeno.descricao}}
        </div>


        <h3>Lideres do Grupo Pequeno: </h3>
        <table  class="ui celled table" >
          <thead>
            <tr>
              <th>Nome</th>
              <th colspan="1"> Opções</th>
            </tr>
          </thead>
          <tbody>
              {% for lider_grupo_pequeno in lider_grupo_pequeno  %}
              <tr>
                <td>{{  lider_grupo_pequeno.nome_completo }}</td>
                <td><a href="{% url 'secretariaapp:liderGrupoPequenoDelete' grupo_pequeno.pk lider_grupo_pequeno.pk  %}" class="ui red button"  > Remover </a> </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{% url 'secretariaapp:liderGrupoPequenoAdicionar' grupo_pequeno.pk 0 %}" class="ui button yellow" > Novo Lider do Grupo Pequeno(PG) </a>
        <p></p>





        <h3>Membros do Grupo Pequeno: </h3>
        <table  class="ui celled table" >
          <thead>
            <tr>
              <th>Nome</th>
              <th colspan="2"> Opções</th>
            </tr>
          </thead>
          <tbody>
              {% for membro in membros  %}
              <tr>
                <td>{{  membro.nome_completo }}</td>
                <td><a href="{% url 'secretariaapp:membro_especifico_no_grupo_pequenoNew' membro.pk  %}" class="ui button" > Editar </a></td>
                <td><a href="{% url 'secretariaapp:remover_membro_pg' membro.pk grupo_pequeno.pk  %}" class="ui red button"  > Remover Membro do Grupo Pequeno (PG) </a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{% url 'secretariaapp:membro_grupo_pequeno_especificoNew' grupo_pequeno.pk %}" class="ui button olive" > Novo Membro No Grupo Pequeno (PG) </a>







        <div class="">
          <h1></h1>
          <a href="{% url 'secretariaapp:grupo_pequenoUpdate' grupo_pequeno.pk  %}" class="ui button" > Editar </a>
          <a href="{% url 'secretariaapp:grupo_pequenoDelete' grupo_pequeno.pk  %}" class="ui red button"  > Deletar</a>
        </div>



</div>
{% include 'rodape.html' %}

secretariaapp/templates/grupos_pequenos.html
{% include 'cabecalho.html' %}
<div class="corpo_app">

<h2>Grupos Pequenos (PG)</h2>

<table class="ui celled table" >
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th colspan="4"> Opções</th>
    </tr>
  </thead>

<a href="{% url 'secretariaapp:grupo_pequenoNew'%}" class="ui button positive" > Novo Grupo Pequeno </a>
<a href="{% url 'secretariaapp:liderGrupoPequenoAdicionar' 0 0 %}" class="ui button yellow" > Novo Lider de Grupo Pequeno </a>
<a href="{% url 'secretariaapp:membro_grupo_pequenoNew'%}" class="ui button olive" > Novo Membro em Grupo Pequeno </a>
  <tbody>
    {% for grupo_pequeno in grupos_pequenos  %}
      <tr>
        <td>{{  grupo_pequeno.nome }}</td>
        <td>{{  grupo_pequeno.descricao }}</td>

        <td> <a href="{% url 'secretariaapp:grupo_pequenoDetalhes' grupo_pequeno.pk  %}" class="ui blue button" > Ver </a> </td>
        <td> <a href="{% url 'secretariaapp:grupo_pequenoUpdate' grupo_pequeno.pk  %}" class="ui button" > Editar </a> </td>
        <td> <a href="{% url 'secretariaapp:grupo_pequenoDelete' grupo_pequeno.pk  %}" class="ui red button"  > Deletar </a> </td>





      </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% include 'rodape.html' %}

secretariaapp/templates/lider_grupo_pequeno_adicionar.html
{% include 'cabecalho.html' %}
<div class="corpo_app">


<h2>Novo Lider de  Grupo Pequeno:  </h2>


<form class="ui form" action="" method="post">{% csrf_token %}

  {% if erro %}
  <div class="ui negative message">
    <ul class="list">
      <b>
        {{ erro }}
      </b>
    </ul>
  </div>
  {% endif %}


  <div class="field">
      <label for="id_grupo_pequeno">Ministério:</label>
        <select name="grupo_pequeno" id="id_grupo_pequeno" required>
          <option value="" selected>Selecione o Grupo Pequeno a Liderar</option>
          {% for grupo_pequeno in grupos_pequenos  %}
              {%if grupo_pequeno_especifico == grupo_pequeno%}
                  <option value="{{grupo_pequeno.pk}}" selected >{{grupo_pequeno.nome}}</option>
              {% else %}
                  <option value="{{grupo_pequeno.pk}}">{{grupo_pequeno.nome}}</option>
              {% endif %}
          {% endfor %}
        </select>
  </div>
<p></p>


<div class="field">
    <label for="id_obreiro">Lider:</label>
      <select name="obreiro" id="id_obreiro" required>
        <option value="" selected>Selecione o Lider</option>
        {% for membro in membros  %}
            {%if membro_especifico == membro%}
                <option value="{{membro.pk}}" selected >{{membro.nome_completo}}</option>
            {% else %}
                <option value="{{membro.pk}}">{{membro.nome_completo}}</option>
            {% endif %}
        {% endfor %}
      </select>
</div>
<p></p>


    <input type="submit" value="Salvar" class="ui button positive" />
    <a href="javascript:window.history.go(-1)" class="ui red button" >Cancelar</a>
</form>

</div>
{% include 'rodape.html' %}

secretariaapp/templates/membros.html
{% include 'cabecalho.html' %}
<div class="corpo_app">

<h2>Membros</h2>


<form class="ui form" action="" method="post">{% csrf_token %}

<div class="field">
    <label><label for="id_situacao">Situação:</label></label>
      <select name="situacao" id="id_situacao" required>
        <option value="{{situacao_ativo.pk}}" selected >{{situacao_ativo.situacao}}</option>
        <option value="0">TODOS</option>
        {% for todas_situacao in todas_situacao  %}
          <option value="{{todas_situacao.pk}}">{{todas_situacao.situacao}}</option>
        {% endfor %}

      </select>
</div>

<div class="field">
<p>
  <label for="id_nome">Nome:</label>
  <input type="text" placeholder="Nome do Membro" name="nome_completo" id="id_nome" maxlength="100" />
</p>
</div>

<input type="submit" value="Pesquisar" class="ui button black" />
</form>
<p></p>


<p>Total de Resultados da Pesquisa: {{qtd}}</p>
<table class="ui celled striped table" >
  <thead>
    <tr>
      <th>Nome</th>
      <th>Situacão</th>
      <th>Data de Nascimento</th>
      <th>Sexo</th>
      <th>Naturalidade</th>
      <th>Celular</th>
      <th>Data Conversão</th>
      <th>Grupo Pequeno</th>
      <th colspan="4"> Opções</th>
    </tr>
  </thead>

<a href="{% url 'secretariaapp:membroNew'%}" class="ui button positive" > Novo Membro </a>

  <tbody>
    {% for membro in membros  %}
      <tr>
        <td>{{  membro.nome_completo }}</td>
        <td>{{  membro.situacao }}</td>
        <td>{%if membro.data_nascimento is not None %}
          {{membro.data_nascimento}}
          {% endif %}
        </td>
        <td>{{  membro.sexo }}</td>
        <td>{{  membro.naturalidade }}</td>
        <td>{{  membro.telefone_celular }}</td>
        <td>{%if membro.data_conversao is not None %}
          {{membro.data_conversao}}
          {% endif %}
        </td>
        <td>{% if membro.grupo_pequeno is not None %}   {{membro.grupo_pequeno}}   {% endif %}</td>

        <td> <a href="{% url 'secretariaapp:membroDetalhes' membro.pk  %}" class="ui blue button" > Ver </a> </td>
        <td> <a href="{% url 'secretariaapp:membroUpdate' membro.pk  %}" class="ui button" > Editar </a> </td>
        <td> <a href="{% url 'secretariaapp:membroDelete' membro.pk  %}" class="ui red button"  > Deletar </a> </td>




      </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% include 'rodape.html' %}

secretariaapp/templates/perfil_detalhes.html
{% include 'cabecalho.html' %}
<div class="corpo_app">

<h2>Perfil do Usuario</h2>
<!--
-->

<h3>Nome do Usuario: {{perfil.user}}</h3>


{% if perfil.nome_completo is not None %}
    <h3>Nome Completo: {{perfil.nome_completo}}</h3>
{% else  %}
    <h3>Nome Completo:</h3>
{% endif  %}


{% if perfil.email is not None %}
  <h3>Email: {{perfil.email}}</h3>
{% else  %}
    <h3>Email:</h3>
{% endif  %}
<p></p>



<table class="ui celled table" >
  <thead>
    <tr>
      <th>Gerenciar Membros</th>
      <th>Gerenciar Grupos Pequenos</th>
      <th>Gerenciar Ministérios</th>
      <th>Relatórios </th>
      <th>Gerenciar Usuarios </th>

    </tr>
  </thead>

  <tbody>
      <tr>
        {% if perfil.gerenciar_Membros  %}
            <td class="positive">Sim</td>
        {% else  %}
            <td class="negative">Não</td>
        {% endif  %}

        {% if perfil.gerenciar_Grupos_Pequenos  %}
            <td class="positive">Sim</td>
        {% else  %}
            <td class="negative">Não</td>
        {% endif  %}

        {% if perfil.gerenciar_Ministerios  %}
            <td class="positive">Sim</td>
        {% else  %}
            <td class="negative">Não</td>
        {% endif  %}

        {% if perfil.gerenciar_Relatorios  %}
            <td class="positive">Sim</td>
        {% else  %}
            <td class="negative">Não</td>
        {% endif  %}

        {% if perfil.gerenciar_Usuarios  %}
            <td class="positive">Sim</td>
        {% else  %}
            <td class="negative">Não</td>
        {% endif  %}

      </tr>
  </tbody>
</table>

 <a href="{% url 'secretariaapp:perfilUpdate' perfil.pk  %}" class="ui button" > Editar Permissões </a>
 <!--<a href="{% url 'secretariaapp:perfilDetalhes' perfil.pk  %}" class="ui blue button" > Visualizar </a>-->
 <a href="{% url 'secretariaapp:userUpdate' perfil.user.pk  %}" class="ui button" > Alterar Usuario </a>
 <a href="{% url 'secretariaapp:userDelete' perfil.user.pk  %}" class="ui red button"  > Deletar </a>

</div>
{% include 'rodape.html' %}

secretariaapp/templates/redirect.html
<html>
 <title>Titulo do site</title>
 <head>
 <meta http-equiv="refresh" content="1;url=https://igrejaelshaday.org">
 </head>
 <body>
   <h1>El Shaday</h1>
 </body>
 </html>